<h3 class="ui-state-error">An error occurred during the uploading process.<br><br>
  When filling in a <strong>technical offer</strong> or an <strong>economic offer</strong>, please note that:
  <ul>
    <li>it is necessary to sign the PDF file generated by the system without any other modification;</li>
    <li>if further documentation is required, other than the offer file generated by the system, it is possible to create a ZIP archive containing all the documentation, digitally signed. Before submitting it, the ZIP archive file must be signed in CAdES format;</li>
    <li>the file generated by the system must <strong>NOT</strong> be printed and scanned for signature, but signed digitally.</li>
  </ul><br>
  If the problem persists, please contact the Technical Help Desk at <strong><?= $_SESSION["numero_assistenza"] ?></strong></h3>
